modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "quick_chat"
version = "${version}"
displayName = "Quick Chat"
authors = "MovTery"
description = "A Minecraft Mod: Send messages quickly by pressing keys."
displayURL = "https://modrinth.com/mod/quick-chat"
logoFile = "icon.png"

[[dependencies.quick_chat]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quick_chat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "quick_chat.mixins.json"
