# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.5.1
group=com.movtery.quick_chat
java_version=17

# Common
minecraft_version=1.20.4
mod_name=Quick Chat
mod_author=MovTery
mod_id=quick_chat
license=MIT
credits=
description=A Minecraft Mod: Send messages quickly by pressing keys.
minecraft_version_range=[1.20.4, 1.20.5)

# Fabric
fabric_version=0.92.1+1.20.4
fabric_loader_version=0.15.3
modmenu=9.2.0
placeholder=2.4.0-pre.1+1.20.4

# Forge
forge_version=49.0.19
forge_loader_version_range=[49,)
forge_version_range=[49,)

# NeoForge
neoforge_version=20.4.83-beta
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
