org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.installations.paths=D:/Tools/Java/azul-17.0.18,D:/Tools/Java/azul-21.0.10,D:/Tools/Java/azul-25.0.2

mod.id=quick_chat
mod.name=Quick Chat
mod.version=1.6.2
mod.group=com.movtery.quick_chat
mod.author=MovTery
mod.license=MIT
mod.description=A Minecraft Mod: Send messages quickly by pressing keys.
